"""Status and type constants — string-based for cross-language portability."""


DEFAULT_BASE = "http://cloud.thumbrella.dev/"

MAX_BACKOFF = 60.0

HTTP_TIMEOUT = 12

HTTP_BACKOFF_TICK = 0.3


class Status:
    """Result statuses.
    
    Defines the overall state of a request. The most common is ``successful``.

    All status will still be provided with a thumbnail image. Some may be a 
    placeholder or failure image.

    See the status documentation at http://thumbrella.dev/docs/status
    """

    SUCCESS = "success"
    FAILED = "failed"
    OVERLOADED = "overloaded"
    INTERMEDIATE = "intermediate"
    UNAVAILABLE = "unavailable"  # Only ever provided by the client


class FileKind:
    """Result media kinds.
    
    Every url will have a kind associated with it. This will be generated by
    sniffing the file contents and file name. This is simpler and more reliable
    than the ``mime`` type attribute each result provides.

    Combined with the result ``extension`` attribute this gives a good 
    indication of the file contents.

    See details about the extensions for each kind at http://thumbrella.dev/docs/kind
    
    """

    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    VECTOR = "vector"
    DOCUMENT = "document"
    GEOMETRY = "geometry"
    ARCHIVE = "archive"
    TEXT = "text"
    BINARY = "binary"
    UNKNOWN = "unknown"


class Source:
    """Defines how a successful thumbnail was processed.
    
    This information is not needed to display or operate the thumbnail. It is
    an internal identifier that describes which code paths the server used to
    generate this image. This can be interesting for accounting or 
    troubleshooting the results.
    
    """

    RENDER = "render"
    SHORTCUT = "shortcut"
    CACHE = "cache"
    NOT_MODIFIED = "not_modified"
    FALLBACK = "fallback"
    PLACEHOLDER = "placeholder"  # No renderer registered for this format
    CLIENT = "client"
