# Pick a custom host url, or put in your own private key, or use the demo site
@host = http://localhost:8788
#@token = tbr_s_localtestingonlysecret  
@token = tbr_s_Y3eBnmmiMHmMGZxTIw1hFQ

### Server check (and token check for main online server)
GET {{host}}/health
Authorization: Bearer {{token}}



### basic get
GET {{host}}/thumb.jpeg?url=https://demo.thumbrella.dev/media/space-colony.jpg
Authorization: Bearer {{token}}



### batch get
POST {{host}}/batch
Content-Type: application/json

{"items":[{"url":"https://demo.thumbrella.dev/media/miss-library.avif"}]}



### usage limit
POST {{host}}/trigger_usage_limit
Authorization: Bearer {{token}}



### direct block
POST http://localhost:8787/api/internal/tokens/1/block
Content-Type: application/json
Origin: http://localhost:8787

{
  "resolution": "daily",
  "requestCount": 10000000
}

