# Pick a custom host url, or put in your own private key, or use the demo site
@host = https://demo.thumbrella.dev
#@host = https://cloud.thumbrella.dev
#@host = http://localhost:3114

@token = none
#@token = tbr_e_3QnzBcWx7KpRmYT2000example


### Server check (and token check for main online server)
GET {{host}}/health
Authorization: Bearer {{token}}


### Thumbnail - simplistic get lookup
GET {{host}}/thumb.jpeg?url=https://demo.thumbrella.dev/media/space-colony.jpg
Authorization: Bearer {{token}}


### Batch (single)
POST {{host}}/batch
Authorization: Bearer {{token}}
Content-Type: application/json

{"items":[{"url":"https://demo.thumbrella.dev/media/miss-library.avif"}]}


### Stream (double)
POST {{host}}/batch
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/ndjson

{"items":[
  {"url":"https://demo.thumbrella.dev/media/harbor-trucks.mp4"}, 
  {"url":"https://demo.thumbrella.dev/media/golden-gate.exr"}]
}
